### ISSUE TITLE
When will the codes be release

### ISSUE THREAD

**Issue by Mooler0410** [hsiehjackson/RULER#1]
Hello! I just read your impressive work! It solved one of my long-standing concerns: Do those "long-context" LLMs truly have real long context windows? I can't wait to test more models using your codebase!

**Comment by Mooler0410** [comment]
Hello! I just read your impressive work! It solved one of my long-standing concerns: Do those "long-context" LLMs truly have real long context windows? I can't wait to test more models using your codebase!

**Comment by hsiehjackson** [comment]
Thanks for your interest! Our code release is still undergoing approval, but we'll release soon!

**Comment by danpadnos** [comment]
Eagerly awaiting the release :)

**Comment by hsiehjackson** [comment]
@Mooler0410 @danpadnos thanks for your patience. we just release our code.
