### ISSUE TITLE
Tempate for Yi?

### ISSUE THREAD

**Issue by liyucheng09** [hsiehjackson/RULER#13]
Great job for this project!

Can we have the template you used for the evaluation of Yi?
Or did you simply use the meta-chat for Yi?

Please let me know for the sake of reproducibility!

**Comment by hsiehjackson** [comment]
@liyucheng09 we use "base" template without any special tokens for the evaluation of Yi.

**Comment by liyucheng09** [comment]
Thanks for your response. Maybe
