### ISSUE TITLE
what was the reason to use nltk in NIAK task here

### ISSUE THREAD

**Issue by vkaul11** [hsiehjackson/RULER#19]
I don't see it being used anywhere else but was curious why nltk.sent_tokenize method has been used here https://github.com/hsiehjackson/RULER/blob/main/scripts/data/synthetic/niah.py#L143 ? How does it help ?

**Comment by hsiehjackson** [comment]
We use `nltk.sent_tokenize` to tokenize contexts into sentences and insert needle statements between sentences. If we don't tokenize contexts into sentences, the needle statements may be inserted in the middle of a sentence which breaking the structure.

**Comment by vkaul11** [comment]
so sent_tokenize identified sentence boundaries and it can work with any hugging face token? Or it uses the internal nltk punkt tokenizer only?

**Comment by hsiehjackson** [comment]
It uses nltk punk tokenizer. If you have some special tokens, then it cannot be separated.
