### ISSUE TITLE
Show Gemini Pro results

### ISSUE THREAD

**Issue by s-macke** [hsiehjackson/RULER#2]
Hi, 

your paper doesn’t show Gemini Pro results with 1M tokens.
Please test against this model.

**Comment by hsiehjackson** [comment]
We are working on testing gemini 1.5 pro. Please stay patient since the API has a restricted rate limit.

**Comment by hsiehjackson** [comment]
@s-macke we just release our codes and put gemini 1.5 pro results in our main table. Thanks for your patience.
