### ISSUE TITLE
Add answer_predfix to prevent model from refusing to answer typo?

### ISSUE THREAD

**Issue by vkaul11** [hsiehjackson/RULER#20]
Do you mean answer_prefix in README. Is this like forced_generation? Model can still refuse to answer.

**Comment by hsiehjackson** [comment]
We add answer prefix as the start tokens of assistant message. This can prevent model from refusing to answer.

**Comment by vkaul11** [comment]
Yes I think there is typo saying answer_predfix which I think is a typo
