### ISSUE TITLE
how do you take care of the presence of 'and' in the output in the evaluation

### ISSUE THREAD

**Issue by vkaul11** [hsiehjackson/RULER#23]
Sometimes the output also can emit "and" for say the multi-value case. Should we not account for that in the output and evaluate the string match accordingly or you never faced such an issue?

3728882, 7210606, 7120868, and 8606962

was my output and my outputs are 
['8606962', '7120868', '3728882', '7210606']

**Comment by hsiehjackson** [comment]
That is fine because our metric checks whether the answers exist in the prediction string.
