### ISSUE TITLE
What is the need for is_icl parameter?

### ISSUE THREAD

**Issue by vkaul11** [hsiehjackson/RULER#25]
I see you set it to false https://github.com/hsiehjackson/RULER/blob/9964f2d7c679c3c7220dd9af44b35c7136795d21/scripts/data/synthetic/variable_tracking.py#L68 here but I don't know the purpose of this parameter.

**Comment by hsiehjackson** [comment]
This parameter helps add a demonstration in our samples. https://github.com/hsiehjackson/RULER/blob/main/scripts/data/synthetic/variable_tracking.py
