### ISSUE TITLE
pre_sample in qa code 

### ISSUE THREAD

**Issue by vkaul11** [hsiehjackson/RULER#29]
I see 
`parser.add_argument("--pre_samples", type=int, default=0, help='number of samples are already generated')` used here for qa
`input_text, answer = generate_input_output(index + args.pre_samples, used_docs)` Why would you ever need this argument?

**Comment by hsiehjackson** [comment]
You can just ignore this parameter. We use this because we run 500 samples evaluation in parallel, and this parameter can help prevent overlapping.
