### ISSUE TITLE
hope add qwen2-7b-chat result

### ISSUE THREAD

**Issue by Chandler-Bing** [hsiehjackson/RULER#46]
thanks for the great project,  hope add  official qwen2-7b-chat result，to compair with glm-4-96-chat.
according to qwen tech report: qwen2 is much better than glm4 on long context evaluation , but I doubt it...

**Comment by hsiehjackson** [comment]
According to Table 12 in Qwen2 tech [report](https://arxiv.org/pdf/2407.10671), if we just evaluate vanilla [Qwen2-7b-128K](https://huggingface.co/Qwen/Qwen2-7B-Instruct) and  [GLM4-9b-1M](https://huggingface.co/THUDM/glm-4-9b-chat-1m), then GLM4 may get better results. However, Qwen2 also proposes Yarn+DCA (training free extension) to boost their performance. I didn't find the codes to run inference with these techniques, so unfortunately I don't have results for comparisons.

**Comment by Chandler-Bing** [comment]
thanks,
