### ISSUE TITLE
Request for permissions

### ISSUE THREAD

**Issue by ChenAlmagor** [hsiehjackson/RULER#61]
Hi @hsiehjackson,
Could you please grant me the necessary access to open PRs? 
I would like to contribute AI21 Jamba model results to the leaderboard and add it as one of the supported models.
Thanks!

**Comment by hsiehjackson** [comment]
Hi @ChenAlmagor I am not sure what permission you need. You are welcome to open any PRs! BTW, I update our main table to show AI21 Jamba-1.5-mini results. It is a pretty strong model!!

**Comment by yuvalbelfer** [comment]
Hey @hsiehjackson ,
Thanks for addingJamba-1.5-Mini!
Can you also add Jamba-1.5-Large? The results are also pretty strong (see section 6.3.1 in our [whitepaper](https://arxiv.org/pdf/2408.12570)).

**Comment by hsiehjackson** [comment]
Sure! Sorry I don't have enough compute to run on my side, so I directly copy numbers from your report!

**Comment by yuvalbelfer** [comment]
Thank you!
