### ISSUE TITLE
Issue with installation: huggingface-hub

### ISSUE THREAD

**Issue by SimJeg** [hsiehjackson/RULER#64]
Hello,

After installing the requirements (`pip install -r requirements.txt`), I had the following error message.

```bash
ImportError: cannot import name 'ModelFilter' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/__init__.py)
```

I used the solution posted [here](https://github.com/NVIDIA/NeMo/issues/9793): 

```bash
pip install huggingface-hub==0.23.2
```

It would be nice to update the requirements.txt file !

**Comment by hsiehjackson** [comment]
Thanks for pointing out. I update our requirements following your suggestion.
